# Generated by Django 4.2.1 on 2023-07-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdata',
        ),
    ]
